#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: autogen
#
Name     : portaudio
Version  : 19.7.0
Release  : 9
URL      : https://github.com/PortAudio/portaudio/archive/refs/tags/v19.7.0.tar.gz
Source0  : https://github.com/PortAudio/portaudio/archive/refs/tags/v19.7.0.tar.gz
Summary  : Portable audio I/O
Group    : Development/Tools
License  : MIT
Requires: portaudio-lib = %{version}-%{release}
Requires: portaudio-license = %{version}-%{release}
BuildRequires : alsa-lib-dev
BuildRequires : pkgconfig(jack)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description


%package dev
Summary: dev components for the portaudio package.
Group: Development
Requires: portaudio-lib = %{version}-%{release}
Provides: portaudio-devel = %{version}-%{release}
Requires: portaudio = %{version}-%{release}

%description dev
dev components for the portaudio package.


%package lib
Summary: lib components for the portaudio package.
Group: Libraries
Requires: portaudio-license = %{version}-%{release}

%description lib
lib components for the portaudio package.


%package license
Summary: license components for the portaudio package.
Group: Default

%description license
license components for the portaudio package.


%prep
%setup -q -n portaudio-19.7.0
cd %{_builddir}/portaudio-19.7.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1693254738
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
%autogen --disable-static --enable-cxx
make

%install
export SOURCE_DATE_EPOCH=1693254738
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/portaudio
cp %{_builddir}/portaudio-%{version}/LICENSE.txt %{buildroot}/usr/share/package-licenses/portaudio/4ee19ebb510fc18b65c179ff2df54ab9bb124f2d || :
cp %{_builddir}/portaudio-%{version}/bindings/cpp/COPYING %{buildroot}/usr/share/package-licenses/portaudio/77bdaf889901b38747bab68f59850dcdf988e957 || :
cp %{_builddir}/portaudio-%{version}/doc/src/license.dox %{buildroot}/usr/share/package-licenses/portaudio/475c65c387c689b04753e811d47bd4929a5603db || :
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/pa_jack.h
/usr/include/pa_linux_alsa.h
/usr/include/portaudio.h
/usr/include/portaudiocpp/AutoSystem.hxx
/usr/include/portaudiocpp/BlockingStream.hxx
/usr/include/portaudiocpp/CFunCallbackStream.hxx
/usr/include/portaudiocpp/CallbackInterface.hxx
/usr/include/portaudiocpp/CallbackStream.hxx
/usr/include/portaudiocpp/CppFunCallbackStream.hxx
/usr/include/portaudiocpp/Device.hxx
/usr/include/portaudiocpp/DirectionSpecificStreamParameters.hxx
/usr/include/portaudiocpp/Exception.hxx
/usr/include/portaudiocpp/HostApi.hxx
/usr/include/portaudiocpp/InterfaceCallbackStream.hxx
/usr/include/portaudiocpp/MemFunCallbackStream.hxx
/usr/include/portaudiocpp/PortAudioCpp.hxx
/usr/include/portaudiocpp/SampleDataFormat.hxx
/usr/include/portaudiocpp/Stream.hxx
/usr/include/portaudiocpp/StreamParameters.hxx
/usr/include/portaudiocpp/System.hxx
/usr/include/portaudiocpp/SystemDeviceIterator.hxx
/usr/include/portaudiocpp/SystemHostApiIterator.hxx
/usr/lib64/libportaudio.so
/usr/lib64/libportaudiocpp.so
/usr/lib64/pkgconfig/portaudio-2.0.pc
/usr/lib64/pkgconfig/portaudiocpp.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libportaudio.so.2
/usr/lib64/libportaudio.so.2.0.0
/usr/lib64/libportaudiocpp.so.0
/usr/lib64/libportaudiocpp.so.0.0.12

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/portaudio/475c65c387c689b04753e811d47bd4929a5603db
/usr/share/package-licenses/portaudio/4ee19ebb510fc18b65c179ff2df54ab9bb124f2d
/usr/share/package-licenses/portaudio/77bdaf889901b38747bab68f59850dcdf988e957
